# Generated by Django 6.0.5 on 2026-06-03 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('organizations', '0012_tariff_discount_enabled_tariff_discount_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinghistory',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='organizations.branch'),
        ),
        migrations.AlterField(
            model_name='billinghistory',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization'),
        ),
    ]
