# Generated by Django 6.0.6 on 2026-06-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbox',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
