# Generated by Django 6.0.6 on 2026-06-20 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_cashbox_s_archived'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashbox',
            old_name='s_archived',
            new_name='is_archived',
        ),
    ]
