# Generated by Django 6.0.6 on 2026-06-22 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('finance', '0003_transaction_financeaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('DIRECT', "To'g'ridan-to'g'ri"), ('BONUS', 'Bonus'), ('PENALTY', 'Jarima'), ('VOUCHER', 'Voucher / Chegirma'), ('SALARY', "Oylik to'lovi")], default='DIRECT', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.student'),
        ),
    ]
