# Generated by Django 6.0.5 on 2026-06-02 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_bonus_branch_cashbox_branch_expense_branch_and_more'),
        ('organizations', '0008_alter_billinghistory_branch_alter_branch_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='organizations.branch'),
        ),
        migrations.AlterField(
            model_name='cashbox',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='organizations.branch'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='organizations.branch'),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='organizations.branch'),
        ),
        migrations.AlterField(
            model_name='expensesubcategory',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='organizations.branch'),
        ),
        migrations.AlterField(
            model_name='fine',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='organizations.branch'),
        ),
        migrations.AlterField(
            model_name='monthlyincome',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='organizations.branch'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='organizations.branch'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='organizations.branch'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='organizations.branch'),
        ),
        migrations.AlterField(
            model_name='teachersalarycalculation',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='organizations.branch'),
        ),
        migrations.AlterField(
            model_name='teachersalaryrule',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='organizations.branch'),
        ),
    ]
