# Generated by Django 6.0.6 on 2026-07-04 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_cashtransaction_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='source_cashtransaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mirrored_transaction', to='finance.cashtransaction'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='source_expense',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mirrored_transaction', to='finance.expense'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='source_payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mirrored_transaction', to='finance.payment'),
        ),
    ]
