# Generated by Django 6.0.5 on 2026-06-06 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0018_alter_attendance_unique_together_and_more'),
        ('finance', '0006_alter_bonus_branch_alter_cashbox_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='academics.student'),
        ),
    ]
