# Generated by Django 6.0.6 on 2026-06-16 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_payment_student'),
        ('organizations', '0017_organization_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_bonus_enabled', models.BooleanField(default=True)),
                ('bonus_types', models.JSONField(blank=True, default=list)),
                ('is_penalty_enabled', models.BooleanField(default=True)),
                ('penalty_types', models.JSONField(blank=True, default=list)),
                ('is_percent_bonus_enabled', models.BooleanField(default=False)),
                ('student_payment_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('debtor_balance_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('is_count_bonus_enabled', models.BooleanField(default=False)),
                ('has_money_students_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('debtor_students_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('kpi_settings', models.JSONField(blank=True, default=dict)),
                ('is_auto_discount_enabled', models.BooleanField(default=False)),
                ('two_groups_discount_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('three_groups_discount_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('four_groups_discount_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='organizations.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StaffSalaryPercent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='organizations.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
