# Generated by Django 6.0.6 on 2026-06-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_financesetting_staffsalarypercent'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffsalarypercent',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Izoh'),
        ),
    ]
