# Generated by Django 6.0.6 on 2026-07-08 12:18

from django.db import migrations, models


def enable_all_notifications(apps, schema_editor):
    TelegramNotificationSetting = apps.get_model('organizations', 'TelegramNotificationSetting')
    TelegramNotificationSetting.objects.update(
        student_payments=True,
        teacher_salaries=True,
        expenses=True,
        other_payments=True
    )

class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramnotificationsetting',
            name='expenses',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='telegramnotificationsetting',
            name='other_payments',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='telegramnotificationsetting',
            name='student_payments',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='telegramnotificationsetting',
            name='teacher_salaries',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(enable_all_notifications, migrations.RunPython.noop),
    ]
