# Generated by Django 6.0.6 on 2026-07-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_telegramnotificationsetting_expenses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramnotificationsetting',
            name='support_bot_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='telegramnotificationsetting',
            name='support_bot_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
