# Generated by Django 6.0.5 on 2026-05-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_examsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsetting',
            name='is_global',
            field=models.BooleanField(default=False),
        ),
    ]
