# Generated by Django 6.0.5 on 2026-05-30 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_examsetting_is_global'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='receipts/')),
                ('hide_logo', models.BooleanField(default=False)),
                ('hide_text_field', models.BooleanField(default=False)),
                ('hide_receipt_number', models.BooleanField(default=False)),
                ('hide_organization_name', models.BooleanField(default=False)),
                ('hide_branch_name', models.BooleanField(default=False)),
                ('hide_student_name', models.BooleanField(default=False)),
                ('hide_phone_number', models.BooleanField(default=False)),
                ('hide_balance', models.BooleanField(default=False)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_setting', to='organizations.organization')),
            ],
        ),
    ]
