# Generated by Django 6.0.6 on 2026-07-14 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_telegramnotificationsetting_support_bot_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramnotificationsetting',
            name='support_contact_link',
            field=models.CharField(blank=True, help_text='Operator Telegram lichkasi (username, masalan: @username)', max_length=255, null=True),
        ),
    ]
