# Generated by Django 6.0.5 on 2026-05-31 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_subscription_balance_tariff_discount_badge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinghistory',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.branch'),
        ),
        migrations.AddField(
            model_name='branch',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.branch'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.branch'),
        ),
    ]
