# Generated by Django 6.0.5 on 2026-06-02 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_alter_billinghistory_branch_alter_branch_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bot_token', models.CharField(blank=True, max_length=255, null=True)),
                ('chat_id', models.CharField(blank=True, max_length=100, null=True)),
                ('api_id', models.CharField(blank=True, max_length=100, null=True)),
                ('api_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('session_string', models.TextField(blank=True, null=True)),
                ('interval_hours', models.IntegerField(choices=[(6, '6 Hours'), (12, '12 Hours'), (24, '24 Hours')], default=24)),
                ('is_active', models.BooleanField(default=False)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='backup_setting', to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
