# Generated by Django 6.0.5 on 2026-06-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_backupsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='available_roles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='organization',
            name='role_permissions',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
