# Generated by Django 6.0.5 on 2026-06-04 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_organization_available_roles_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramNotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bot_token', models.CharField(blank=True, max_length=255, null=True)),
                ('chat_ids', models.TextField(blank=True, help_text="Vergul bilan ajratilgan chat ID'lar", null=True)),
                ('student_payments', models.BooleanField(default=False)),
                ('teacher_salaries', models.BooleanField(default=False)),
                ('expenses', models.BooleanField(default=False)),
                ('other_payments', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_notification_setting', to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
