# Generated by Django 6.0.5 on 2026-06-04 08:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0011_telegramnotificationsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='discount_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tariff',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='tariff',
            name='student_limit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='BillingHistory',
        ),
    ]
