# Generated by Codex on 2026-06-05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0012_tariff_discount_enabled_tariff_discount_percent_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExamSetting',
        ),
    ]
