# Generated by Django 6.0.5 on 2026-06-06 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0013_delete_examsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('include_active_students', models.BooleanField(default=True)),
                ('include_trial_students', models.BooleanField(default=True)),
                ('include_archived_students', models.BooleanField(default=False)),
                ('include_frozen_students', models.BooleanField(default=False)),
                ('include_deleted_students', models.BooleanField(default=False)),
                ('is_global', models.BooleanField(default=False)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exam_setting', to='organizations.organization')),
            ],
        ),
    ]
