# Generated by Django 6.0.6 on 2026-06-10 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0014_examsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonNotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('template_type', models.CharField(choices=[('before', 'Dars boshlanishidan oldin'), ('during', 'Dars davomida'), ('after', 'Dars tugagandan keyin')], max_length=20)),
                ('delay_minutes', models.IntegerField(default=5)),
                ('message_text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='organizations.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
