# Generated by Django 6.0.6 on 2026-06-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0015_lessonnotificationtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramnotificationsetting',
            name='parent_bot_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='telegramnotificationsetting',
            name='parent_bot_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='telegramnotificationsetting',
            name='staff_bot_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='telegramnotificationsetting',
            name='staff_bot_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='telegramnotificationsetting',
            name='student_bot_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='telegramnotificationsetting',
            name='student_bot_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='telegramnotificationsetting',
            name='verification_bot_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='telegramnotificationsetting',
            name='verification_bot_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
