# Generated by Django 6.0.6 on 2026-06-16 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0016_telegramnotificationsetting_parent_bot_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
