# Generated by Django 6.0.6 on 2026-06-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0017_organization_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
