# Generated by Django 6.0.6 on 2026-07-15 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_telegram_language'),
        ('organizations', '0004_telegramnotificationsetting_support_contact_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='assigned_users', to='organizations.branch', verbose_name='Biriktirilgan filiallar'),
        ),
    ]
