# Generated by Django 6.0.5 on 2026-06-02 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_birth_date_user_gender_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('manager', 'Manager'), ('teacher', 'Teacher'), ('receptionist', 'Receptionist'), ('employee', 'Employee'), ('student', 'Student')], default='employee', max_length=20),
        ),
    ]
