# Generated by Django 6.0.6 on 2026-06-17 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_telegram_chat_id'),
        ('finance', '0008_financesetting_staffsalarypercent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='salary_percentage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='finance.staffsalarypercent', verbose_name='Oladigan foizi'),
        ),
    ]
