# Generated by Django 6.0.5 on 2026-05-31 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
        ('organizations', '0007_billinghistory_branch_branch_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsmessages',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.branch'),
        ),
        migrations.AddField(
            model_name='smsprovider',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.branch'),
        ),
        migrations.AddField(
            model_name='smsschedules',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.branch'),
        ),
        migrations.AddField(
            model_name='smstemplates',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.branch'),
        ),
    ]
