# Generated by Django 6.0.5 on 2026-06-04 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_alter_smsmessages_branch_alter_smsprovider_branch_and_more'),
        ('organizations', '0012_tariff_discount_enabled_tariff_discount_percent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkSMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('sent_by', models.CharField(blank=True, max_length=255, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('total_sent', models.IntegerField(default=0)),
                ('total_failed', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('organizations', models.ManyToManyField(blank=True, help_text="Bo'sh qolsa — hamma organizationlarga yuboriladi", to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('subscription_expiry', 'Tarif tugashidan oldin'), ('balance_low', 'Balance kam'), ('info', 'Umumiy xabar')], default='info', max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('subscription_expiry', 'Tarif tugashidan oldin'), ('balance_low', 'Balance kam qolganda')], max_length=50)),
                ('days_before', models.IntegerField(default=3, help_text='Necha kun oldin eslatsin (faqat subscription_expiry uchun)')),
                ('balance_threshold', models.DecimalField(decimal_places=2, default=0, help_text="Qancha balancedan kam bo'lsa eslatsin (faqat balance_low uchun)", max_digits=12)),
                ('custom_message', models.TextField(blank=True, help_text="Template yo'q bo'lsa shu xabar yuboriladi", null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='communication.smstemplates')),
            ],
        ),
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('status', models.CharField(default='sent', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='organizations.organization')),
                ('reminder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='communication.subscriptionreminder')),
            ],
        ),
    ]
