# Generated by Django 6.0.5 on 2026-06-04 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0004_bulksms_notification_subscriptionreminder_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('subscription_expiry', 'Tarif tugashidan oldin'), ('balance_low', 'Balance kam'), ('info', 'Umumiy xabar'), ('birthday_reminder', "Tug'ilgan kun eslatmasi")], default='info', max_length=50),
        ),
    ]
