# Generated by Django 6.0.5 on 2026-06-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0006_notificationschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationschedule',
            name='delivery_mode',
            field=models.CharField(choices=[('immediate', 'Immediate'), ('scheduled', 'Scheduled')], default='scheduled', max_length=20),
        ),
        migrations.AddField(
            model_name='notificationschedule',
            name='target_course_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='notificationschedule',
            name='target_group_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
