# Generated by Django 6.0.5 on 2026-06-06 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0007_notificationschedule_delivery_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationschedule',
            name='send_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
