# Generated by Django 6.0.6 on 2026-06-25 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_item_is_completed_item_members_item_start_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='item',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
