# Generated by Django 6.0.5 on 2026-05-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_lead_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
