# Generated by Django 6.0.5 on 2026-06-02 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_crmactivity_branch_crmleadlost_branch_and_more'),
        ('organizations', '0008_alter_billinghistory_branch_alter_branch_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmactivity',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='organizations.branch'),
        ),
        migrations.AlterField(
            model_name='crmleadlost',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='organizations.branch'),
        ),
        migrations.AlterField(
            model_name='crmleadshistory',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='organizations.branch'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='organizations.branch'),
        ),
        migrations.AlterField(
            model_name='leadform',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='organizations.branch'),
        ),
        migrations.AlterField(
            model_name='lostreason',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='organizations.branch'),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='organizations.branch'),
        ),
        migrations.AlterField(
            model_name='section',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='organizations.branch'),
        ),
        migrations.AlterField(
            model_name='source',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='organizations.branch'),
        ),
    ]
