# Generated by Django 6.0.5 on 2026-06-06 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_lead_contacted_at_lead_next_contact_at_lead_notes_and_more'),
        ('organizations', '0014_examsetting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='reminder_deadline',
            field=models.DateTimeField(blank=True, help_text='Lidning muddati (Sana va vaqt)', null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='crm.pipeline'),
        ),
        migrations.AlterField(
            model_name='section',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='crm.pipeline'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['organization', 'is_archived'], name='crm_lead_organiz_c16a9c_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['pipeline'], name='crm_lead_pipelin_e68a31_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['source'], name='crm_lead_source__21714c_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status'], name='crm_lead_status_2c1bc7_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['phone'], name='crm_lead_phone_8180e8_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['name'], name='crm_lead_name_977dba_idx'),
        ),
        migrations.AddField(
            model_name='leadcomment',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='organizations.branch'),
        ),
        migrations.AddField(
            model_name='leadcomment',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_comments', to='crm.lead'),
        ),
        migrations.AddField(
            model_name='leadcomment',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='leadcomment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
