# Generated by Django 6.0.6 on 2026-06-15 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_leadcomment_lead_reminder_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadform',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='lead_forms/covers/'),
        ),
        migrations.AddField(
            model_name='leadform',
            name='header_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Asosiy matn'),
        ),
        migrations.AddField(
            model_name='leadform',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='lead_forms/logos/'),
        ),
        migrations.AddField(
            model_name='leadform',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.pipeline'),
        ),
        migrations.AddField(
            model_name='leadform',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.section'),
        ),
        migrations.AddField(
            model_name='leadform',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.source'),
        ),
        migrations.AddField(
            model_name='leadform',
            name='success_text',
            field=models.TextField(default="Ma'lumotlaringiz muvaffaqiyatli yuborildi!", verbose_name='Yuborilgandan keyingi matn'),
        ),
        migrations.AddField(
            model_name='leadform',
            name='theme_color',
            field=models.CharField(default='#e28743', max_length=30, verbose_name='Forma rangi (Hex code)'),
        ),
        migrations.AlterField(
            model_name='leadform',
            name='fields',
            field=models.JSONField(blank=True, default=list, help_text='[{"name": "name", "label": "Ism", "required": true}]'),
        ),
        migrations.AlterField(
            model_name='leadform',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Forma nomi'),
        ),
    ]
