# Generated by Django 6.0.6 on 2026-06-17 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0033_group_assistant_teacher_group_days_and_more'),
        ('crm', '0011_leadform_cover_image_leadform_header_text_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='debt_limit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Qarzdorlik limiti'),
        ),
        migrations.AddField(
            model_name='lead',
            name='moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_crm_leads', to=settings.AUTH_USER_MODEL, verbose_name='Biriktirilgan moderator'),
        ),
        migrations.AddField(
            model_name='lead',
            name='parent_login',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='parent_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_crm_leads', to='academics.student', verbose_name="Referal bergan o'quvchi"),
        ),
        migrations.AddField(
            model_name='lead',
            name='student_login',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='student_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('won', 'Won'), ('lost', 'Lost'), ('first_lesson', 'Birinchi darsga yozilganlar')], default='open', max_length=20),
        ),
    ]
