# Generated by Django 6.0.6 on 2026-07-01 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Material nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('material_type', models.CharField(choices=[('video', 'Video'), ('file', 'Fayl (PDF, Word va b.)'), ('link', 'Havola (Link)'), ('image', 'Rasm'), ('text', 'Matn')], default='file', max_length=20, verbose_name='Material turi')),
                ('file', models.FileField(blank=True, null=True, upload_to='course_materials/', verbose_name='Fayl')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Video havolasi')),
                ('external_link', models.URLField(blank=True, null=True, verbose_name='Tashqi havola')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('is_published', models.BooleanField(default=True, verbose_name='Nashr qilinganmi?')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='organizations.branch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='academics.course', verbose_name='Kurs')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
