# Generated by Django 5.2.14 on 2026-05-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_balancehistory_exam_examresult_leavereason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
