# Generated by Django 6.0.6 on 2026-07-01 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_add_course_material_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinelesson',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_lessons', to='academics.group'),
        ),
    ]
