# Generated by Django 5.2.14 on 2026-05-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_course_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lesson_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
