# Generated by Django 6.0.6 on 2026-07-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_alter_onlinelesson_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
