# Generated by Django 6.0.6 on 2026-07-16 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_alter_botmessagetemplate_template_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroupleave',
            name='student_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentgroupleave',
            name='student_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
