# Generated by Django 6.0.5 on 2026-05-30 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_studentarchive'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academics.group'),
        ),
        migrations.AddField(
            model_name='exam',
            name='max_score',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='exam',
            name='min_score',
            field=models.IntegerField(default=60),
        ),
    ]
