# Generated by Django 6.0.5 on 2026-06-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_studentgroup_price_alter_attendance_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroupleave',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentgroupleave',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentgroupleave',
            name='refound_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
