# Generated by Django 6.0.5 on 2026-06-04 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_studentgroupleave_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='student_photos/'),
        ),
    ]
