# Generated by Django 6.0.5 on 2026-06-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_student_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroupleave',
            name='is_sent_to_leads',
            field=models.BooleanField(default=False),
        ),
    ]
