# Generated by Django 6.0.6 on 2026-06-10 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0019_student_address_student_application_and_more'),
        ('organizations', '0015_lessonnotificationtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFieldSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_name', models.CharField(choices=[('last_name', 'Familiya'), ('email', 'Elektron pochta'), ('photo', 'Rasm'), ('category', 'Kategoriya'), ('birth_date', "Tug'ilgan sana"), ('application', "So'rovnoma"), ('language', 'Til'), ('payment_date', "To'lov sanasi"), ('address', 'Uy manzili'), ('target_university', 'Maqsad qilgan universitet'), ('organization', 'Tashkilot'), ('father_name', 'Otasining ismi'), ('father_phone', 'Otasining telefon raqami'), ('father_email', 'Otasining elektron pochtasi'), ('mother_name', 'Onasining ismi'), ('mother_phone', 'Onasining telefon raqami'), ('mother_email', 'Onasining elektron pochtasi')], max_length=100)),
                ('is_required', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='organizations.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_field_settings', to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
