# Generated by Django 6.0.6 on 2026-06-11 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0020_studentfieldsetting'),
        ('organizations', '0015_lessonnotificationtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='desired_organization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization'),
        ),
    ]
