# Generated by Django 6.0.6 on 2026-06-11 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0021_student_desired_organization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='desired_organization',
        ),
    ]
