# Generated by Django 6.0.6 on 2026-06-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0022_remove_student_desired_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=6)),
                ('purpose', models.CharField(choices=[('register', 'Ro‘yxatdan o‘tish'), ('forgot', 'Parolni tiklash')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
