# Generated by Django 6.0.6 on 2026-06-11 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0023_telegramverification'),
        ('organizations', '0015_lessonnotificationtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram Chat ID'),
        ),
        migrations.CreateModel(
            name='BotMessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150, verbose_name='Shablon nomi')),
                ('template_type', models.CharField(choices=[('remind', 'Dars eslatmasi (Darsga chaqiriq)'), ('payment_due', 'To‘lov vaqti kelganda ogohlantirish'), ('payment_success', 'To‘lov muvaffaqiyatli bo‘lganda chek'), ('news', 'Umumiy yangiliklar')], max_length=30, verbose_name='Turi')),
                ('text', models.TextField(help_text="O'zgaruvchilarni mana bunday yozing: {first_name}, {balance}, {course_name}, {hours}", verbose_name='Xabar matni')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='organizations.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Bot Xabar Shabloni',
                'verbose_name_plural': 'Bot Xabar Shablonlari',
                'unique_together': {('organization', 'template_type')},
            },
        ),
    ]
