# Generated by Django 6.0.6 on 2026-06-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0024_student_telegram_chat_id_botmessagetemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botmessagetemplate',
            name='template_type',
            field=models.CharField(choices=[('remind', 'Dars eslatmasi (Darsga chaqiriq)'), ('payment_due', 'To‘lov vaqti kelganda ogohlantirish'), ('payment_success', 'To‘lov muvaffaqiyatli bo‘lganda chek'), ('news', 'Umumiy yangiliklar'), ('parent_check_in', 'Ota-ona: Farzandi darsga kelganda'), ('parent_check_out', 'Ota-ona: Dars tugaganda (ketganda)'), ('parent_exam_result', 'Ota-ona: Imtihon baholari chiqganda'), ('parent_payment_due', 'Ota-ona: To‘lov vaqti kelganda')], max_length=30, verbose_name='Turi'),
        ),
    ]
