# Generated by Django 6.0.6 on 2026-06-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0025_alter_botmessagetemplate_template_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botmessagetemplate',
            name='template_type',
            field=models.CharField(choices=[('remind', 'Dars eslatmasi (Darsga chaqiriq)'), ('payment_due', 'To‘lov vaqti kelganda ogohlantirish'), ('payment_success', 'To‘lov muvaffaqiyatli bo‘lganda chek'), ('news', 'Umumiy yangiliklar'), ('parent_check_in', 'Ota-ona: Farzandi darsga kelganda'), ('parent_check_out', 'Ota-ona: Dars tugaganda (ketganda)'), ('parent_exam_result', 'Ota-ona: Imtihon baholari chiqganda'), ('parent_payment_due', 'Ota-ona: To‘lov vaqti kelganda'), ('staff_general_news', 'Xodimlar: Boshliqdan umumiy xabar/topshiriq'), ('staff_salary_remind', 'Xodimlar: Oylik to‘lov eslatmasi'), ('staff_holiday_remind', 'Xodimlar: Bayram va dam olish kuni eslatmasi')], max_length=30, verbose_name='Turi'),
        ),
    ]
