# Generated by Django 6.0.6 on 2026-06-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0026_alter_botmessagetemplate_template_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='father_telegram_chat_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Otasining Telegram Chat IDsi'),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_telegram_chat_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Onasining Telegram Chat IDsi'),
        ),
    ]
