# Generated by Django 6.0.6 on 2026-06-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0027_student_father_telegram_chat_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='botmessagetemplate',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='botmessagetemplate',
            name='target_audience',
            field=models.CharField(choices=[('leads', 'Lidlar (CRM)'), ('students', 'Talabalar (Academics)'), ('staff', 'Xodimlar (Staff)')], default='students', max_length=20, verbose_name='Kimlar uchun'),
        ),
        migrations.AlterField(
            model_name='botmessagetemplate',
            name='template_type',
            field=models.CharField(choices=[('lead_marketing', 'Lid: Reklama/Aksiya xabari'), ('lead_holiday', 'Lid: Bayram tabrigi'), ('lead_followup', 'Lid: Qayta aloqa/Eslatma'), ('remind', 'Talaba: Dars eslatmasi (Darsga chaqiriq)'), ('payment_due', 'Talaba: To‘lov vaqti kelganda ogohlantirish'), ('payment_success', 'Talaba: To‘lov muvaffaqiyatli bo‘lganda chek'), ('news', 'Talaba: Umumiy yangiliklar'), ('parent_check_in', 'Ota-ona: Farzandi darsga kelganda'), ('parent_check_out', 'Ota-ona: Dars tugaganda (ketganda)'), ('parent_exam_result', 'Ota-ona: Imtihon baholari chiqganda'), ('parent_payment_due', 'Ota-ona: To‘lov vaqti kelganda'), ('staff_general_news', 'Xodimlar: Boshliqdan umumiy xabar/topshiriq'), ('staff_salary_remind', 'Xodimlar: Oylik to‘lov eslatmasi'), ('staff_holiday_remind', 'Xodimlar: Bayram va dam olish kuni eslatmasi')], max_length=30, verbose_name='Turi'),
        ),
        migrations.AlterField(
            model_name='botmessagetemplate',
            name='text',
            field=models.TextField(help_text="O'zgaruvchilarni jingalak qavs ichida yozing, masalan: {first_name}, {balance}, {section_name}", verbose_name='Xabar matni'),
        ),
    ]
