# Generated by Django 6.0.6 on 2026-06-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0028_alter_botmessagetemplate_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Dars izohi/tavsifi'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dars mavzusi'),
        ),
        migrations.AddField(
            model_name='onlinelesson',
            name='attendance_date',
            field=models.DateField(blank=True, null=True, verbose_name="Bog'langan dars sanasi"),
        ),
        migrations.AddField(
            model_name='onlinelesson',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Dars tavsifi'),
        ),
        migrations.AlterField(
            model_name='onlinelesson',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
