# Generated by Django 6.0.6 on 2026-06-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0029_attendance_description_attendance_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_canceled',
            field=models.BooleanField(default=False, verbose_name='Dars bekor qilinganmi?'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='original_date',
            field=models.DateField(blank=True, null=True, verbose_name="Darsning asl (ko'chirilishdan oldingi) sanasi"),
        ),
    ]
