# Generated by Django 6.0.6 on 2026-06-15 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0030_attendance_is_canceled_attendance_original_date'),
        ('organizations', '0016_telegramnotificationsetting_parent_bot_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='description',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='is_canceled',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='original_date',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='title',
        ),
        migrations.CreateModel(
            name='GroupLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='Dars sanasi')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dars mavzusi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Dars izohi')),
                ('is_canceled', models.BooleanField(default=False, verbose_name='Dars bekor qilinganmi?')),
                ('original_date', models.DateField(blank=True, null=True, verbose_name='Asl sanasi')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='organizations.branch')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='academics.group')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
