# Generated by Django 6.0.6 on 2026-06-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0033_group_assistant_teacher_group_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='referred_by',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kim tavsiya qildi'),
        ),
    ]
