# Generated by Django 6.0.6 on 2026-06-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0034_student_referred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='debt_limit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Qarzdorlik limiti'),
        ),
        migrations.AddField(
            model_name='student',
            name='moderator',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_login',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_login',
            field=models.CharField(blank=True, null=True),
        ),
    ]
